---
title: "Entregable Mapas Natalia Gavaldá"
author: "Natalia Gavaldá"
date: "2024-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librerías


```{r Librerías, warning=FALSE}
library(maps)
library(ggplot2)
library(tidyverse)
library(RColorBrewer)
library(dplyr)
```

## Pasos previos 

```{r pp, warning=FALSE}
# Definición de países
Europa = c(
  "Portugal", "Spain", "France", "Switzerland", "Germany",    "Austria", "UK", "Netherlands",
  "Denmark", "Poland", "Italy",  "Croatia", "Slovenia", "Hungary", "Slovakia",  "Czech republic",
  "Sweden","Finland", "Norway","Estonia", "Lithuania", "Ukraine",    "Belarus", "Romania",
  "Belgium", "Bulgaria", "Greece", "Moldova", "Latvia","Luxembourg","Serbia", "Bosnia and
Herzegovina", "North Macedonia", "Montenegro", "Albania","Ireland","Kosovo"
)

# Datos
datos_europa <- map_data("world", region = Europa)

# Puntos a señalar en el gráfico
ciudades <- c("Lisboa","Madrid", "Paris","Roma")
longitud<-c( -9.1333300,-3.70256,2.3488,11.71819)
latitud <-c( 38.71667, 40.4165, 48.85341, 45.58383)

# DF con los puntos a señalar en el gráfico
coordenadas = data.frame(
  longitud = longitud,
  latitud = latitud,
  stringAsFactors = F
)

# DF con el centro del país
centro_del_pais <- datos_europa %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))
```

## Grafico


```{r Grafico, warning=FALSE}
ggplot() + 
  geom_polygon(data = datos_europa, aes(x = long, y = lat, group=group),
                   fill = "#D62839", 
                   color = "black", 
                   alpha = 0.5
                   ) +
  geom_text(data = coordenadas, 
            aes(x = longitud, y = latitud, label = ciudades), 
           color = "red", size = 3) +
  geom_text(data = centro_del_pais, 
            aes(x = long, y = lat, label = region), 
            color = "black", size = 3, check_overlap = TRUE) +
  labs(title = "Mapa de Europa", subtitle = "Algunas capitales",
       x = "Longitud", y = "Latitud") +
  theme_minimal() 
```


